name: Update Post Dates

on:
  push:
    branches:
      - main
    paths:
      - 'src/content/posts/**'

jobs:
  update-dates:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 git 히스토리를 가져옴
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install gray-matter
          
      - name: Update Post Dates
        run: |
          echo "Running update-post-dates script..."
          node .github/scripts/update-post-dates.js
          echo "Script completed."
          
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          if [[ -n "$(git status --porcelain src/content/posts/)" ]]; then
            echo "Changes detected in posts directory"
            git add src/content/posts/
            git commit -m "chore: Update post dates"
            git push
          else
            echo "No changes to commit"
          fi 